### ISSUE TITLE
为啥 没正版进不了

### ISSUE THREAD

**Issue by danchei** [YuanXiaCN/CradyCraft#6]
为什么

**Comment by YuanXiaCN** [comment]
请多次尝试连接服务器，若仍然无法连接，请再次提交issues并附上log

**Comment by YuanXiaCN** [comment]
已修复，感谢您的反馈

**Comment by LINKlang** [comment]
> 已修复，感谢您的反馈

~~复活吧，我的爱人[中二~~
~~以下为离线测试~~
![image](https://github.com/YuanXiaCN/CradyCraft/assets/116951234/17b4b7a5-97d1-4d4e-b85c-779b9234f3bd)

额，复活失败了，又好了
